# Generated by Django 2.0rc1 on 2018-01-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emailconfirmed_hashkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmed',
            old_name='hashkey',
            new_name='key',
        ),
    ]
