# Generated by Django 2.0rc1 on 2018-01-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180105_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmed',
            name='key',
            field=models.CharField(max_length=120),
        ),
    ]
