# Generated by Django 2.0rc1 on 2017-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171227_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://img.michaels.com/L6/3/IOGLO/873480063/212543238/10093626_r.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
