# Generated by Django 2.0rc1 on 2017-12-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20171230_1953'),
        ('cart', '0003_auto_20171229_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Variation'),
        ),
    ]
